controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\controllers\CustomController;


class SiteController extends CustomController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    public $Password;

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // вытащить все
        ///$model = Category::find()->all();

        // вытаскиваем запись с id = 6
        //$model = Category::findOne(6);
        //$model = Category::find()->where(['id' => 6])->all();

        // вытаскиваем 3 первых записи
        //$model = Category::find()->limit(3)->all();

        //вытаскиваем 3 последних записи
        //$model = Category::find()->orderBy('id DESC')->limit(3)->all();

        return $this->render('index'/*, compact('model')*/);
    }




    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionRegistrationLogin()
    {
        if (!Yii::$app->user->isGuest)
        {
            return $this->goHome();
        }



        $this->setMeta('Регистрация/Авторизация');

        $registration = new User();

        $registration->scenario = 'registration';

        $login = new User();

        $login->scenario = 'login';

        if($login->load(Yii::$app->request->post()) && $login->login())
        {
            return $this->goHome();
        }


        if($registration->load(Yii::$app->request->post()))
        {


            if (!User::find()->where(['email' => $registration->email])->limit(1)->all())
            {
                $this->Password = $registration->password;

                $registration->password = Yii::$app->security->generatePasswordHash($registration->password);
                $registration->code = Yii::$app->getSecurity()->generateRandomString(10);


                if($registration->save())
                {
                    $registration->sendCongirmationLink();
                    Yii::$app->session->setFlash('success', 'Вам  отправлена ссылка с потверждением вашего Email');
                    return $this->goHome();
                }
                else
                {

                    $registration->password = $this->Password;
                    return $this->render('reglog', compact('registration'));
                }
            }
            else
            {
                Yii::$app->session->setFlash('info', 'Пользователь с таким Email существует, попробуйте востановить пароль.');
                return $this->goHome();
            }



        }



        return $this->render('reglog', compact('registration', 'login'));

    }


    public function actionConfirmemail()
    {
        $code = Yii::$app->request->get('code');
        $email = Yii::$app->request->get('email');

        if (!Yii::$app->user->isGuest)
        {
            return $this->goHome();
        }

        $user = User::find()->where(['code' => $code, 'email' => $email])->one();

        if($user->active == 0)
        {
            $user->code = '';
            $user->active = User::ACTIVE_USER;

            if($user->save())
            {
                $user->login();
                Yii::$app->session->setFlash('success', 'Аккаунт активирован');
                return $this->goHome();
            }

        }
        else
        {

            Yii::$app->session->setFlash('error', 'Не удалось активировать аккаунт, обратитесь к Администрации сайта.');
            return $this->goHome();
        }
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/main.php
<?php
/**
 * Created by PhpStorm.
 * User: медведь
 * Date: 10.12.2017
 * Time: 0:44
 */
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use app\widgets\CategoryMenu;
$route = Yii::$app->controller->route;
$url = Yii::$app->request->resolve();

//\app\controllers\CustomController::printr($route);
//\app\controllers\CustomController::printr($url);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie ie6 ie-lt10 ie-lt9 ie-lt8 ie-lt7 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 ie-lt10 ie-lt9 ie-lt8 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 ie-lt10 ie-lt9 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 ie-lt10 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <!--[if LTE IE 8]>
    <link rel="stylesheet" type="text/css" href="/css/minimal-menu-ie.css" />
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="/js/libs/html5shiv.js"></script>
    <script src="/js/libs/respond.js"></script>
    <![endif]-->
    <?php $this->head() ?>
</head>
<body class="home">
<?php $this->beginBody() ?>
<div class="topbar">
    <div class="container">
        <div class="left-topbar">
            Добро пожаловать Вы можете <a href="<?=  Url::to(['/site/registration-login']) ?>">авторизоваться</a> или  <a href="<?=  Url::to(['/site/registration-login']) ?>">зарегистрироваться</a>.
        </div>
        <!-- /.left-topbar -->
        <ul class="right-topbar">

            <?php if(!Yii::$app->user->isGuest) : ?>

            <li><a href="<?= Url::to(['site/logout']) ?>">Выйти</a></li>

            <?php endif; ?>

            <li>
                <a href="#" class="top-wishlist">
                    Wish list
                    <span>5</span>
                </a>
            </li>
            <li><a href="#">My account</a></li>
            <li><a href="#">Shopping Cart</a></li>
            <li><a href="#">Check out</a></li>
        </ul>
        <!-- /.right-topbar -->
    </div>
</div>
<!-- /.topbar -->
<header>
    <div class="container">
        <a class="logo" href="/">
            <img src="/images/logo.png" alt="img" />
        </a>
        <!-- /.logo -->
        <nav class="main-nav">
            <div class="minimal-menu">
                <ul class="menu">
                    <li class="current-menu-item"><a href="<?= Url::to(['/']) ?>">Главная</a></li>
                    <!--<li><a href="category.html">T-SHIRT</a></li>
                    <li><a href="category.html">WOMEN</a></li>-->
                    <?= CategoryMenu::widget(['view' => 'glMenu']) ?>
                    <li><a href="category.html">ACCESSORIES</a></li>
                </ul>
            </div>
            <!-- /.minimal-menu -->
        </nav>
        <!-- /.main-nav -->
        <div class="wrap-search">
            <form action="#" class="search-form">
                <input type="text" placeholder="Search Bags.." />
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
        <!-- /.search-form -->
        <div class="top-cart">
            <a href="cart.html">
                YOUR CART
                <span>2</span>
            </a>
        </div>
        <!-- /.top-cart -->
    </div>
</header>

<?= Alert::widget() ?>
<?= $content ?>


<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6 left-footer clearfix">
                <h3>Join Our Communication</h3>
                <ul class="list-social">
                    <li><a class="facebook" href="#">facebook</a></li>
                    <li><a class="twitter" href="#">twitter</a></li>
                    <li><a class="googleplus" href="#">googleplus</a></li>
                    <li><a class="pinterest" href="#">pinterest</a></li>
                    <li><a class="instagram" href="#">instagram</a></li>
                </ul>
            </div>
            <div class="col-md-6 right-footer">
                <div class="clearfix">
                    <div class="wrap-select-currency">
                        <select class="custom-select currency-switch">
                            <option value="0">USD</option>
                            <option value="1">Euro</option>
                        </select>
                    </div>
                    <div class="wrap-select-country">
                        <select class="custom-select country-switch">
                            <option value="0" data-icon="us-flag">United States</option>
                            <option value="1" data-icon="fr-flag">France</option>
                            <option value="2" data-icon="de-flag">Germany</option>
                            <option value="3" data-icon="it-flag">Italy</option>
                        </select>
                    </div>
                </div>
                <p class="copyright">© 2014 Designed by <a href="#"><strong>Kidesigner</strong></a>. All rights reserved</p>
            </div>
        </div>
    </div>
</footer>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>